site_name: Lorentz Symmetry Violations of Superluminal Jets
theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes

nav:
  - Home: index.md
  - Scripts:
    - scripts/index.md
    - Anisotropic Model: scripts/PyMC_Pytensor_noise_v_main_varsig_aniso.md
    - Isotropic Model: scripts/iso_model.md
    - Data Generator: scripts/data_gen.md
    - Simulation Import: scripts/simulation_import.md
    - MOJAVE Scraper: scripts/mojave_scraper.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
          paths: ["scripts"]

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
